# Generated by Django 6.0.3 on 2026-04-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enrollment_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
